server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/zepto_test
    username: root
    password: root

  jpa:
    show-sql: true
  
    hibernate:
      ddl-auto: update
      
     
  zipkin:
    base-url: http://localhost:9411
    enabled: true
  sleuth:
    sampler:
      probability: 1.0
    propagation-keys:
      - b3
      - X-B3-TraceId
      - X-B3-SpanId
      - X-B3-ParentSpanId
      - X-B3-Sampled
      - X-B3-Flags
  
  logging:
    pattern:
        console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %5p [${spring.application.name},%X{traceId},%X{spanId}] %logger{36} - %msg%n"

#(zepto-payment-config)