server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/zepto_test
    username: root
    password: root

  jpa:
    show-sql: true
  
    hibernate:
      ddl-auto: update
#(zepto-payment-config)